pipeline:
  maven:
    image: maven:3.5-alpine
    commands:
      - mvn clean package -f bakery-app/pom.xml
#    volumes:
#      - ${HOME}/.m2:/root/.m2

  docker-image-worker:
#    group: docker-images
    image: plugins/docker
    repo: toschneck/bakery-worker-drone
    tag: ${DRONE_REPO_BRANCH}
    secrets: [ docker_username, docker_password ]
    dockerfile: bakery-app/Dockerfile.worker.drone
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
  docker-image-web:
#    group: docker-images
    image: plugins/docker
    repo: toschneck/bakery-web-drone
    tag: ${DRONE_REPO_BRANCH}
    secrets: [ docker_username, docker_password ]
    dockerfile: bakery-app/Dockerfile.web.drone
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
  docker-image-report:
#    group: docker-images
    image: plugins/docker
    repo: toschneck/bakery-report-drone
    tag: ${DRONE_REPO_BRANCH}
    secrets: [ docker_username, docker_password ]
    dockerfile: bakery-app/Dockerfile.report.drone
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

