apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvhost001
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-vol
  namespace: drone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi