version: '2'

networks:
  default:
    external:
      name: bakery-network

services:
  citrus_basic:
      container_name: citrus-it-test
      #image: consol/sakuli-ubuntu-xfce:v1.1.0-beta
      # for custom sakuli test client
      build:
        context: .
      cpu_quota: 75000
      mem_reservation: 600MB
      volumes:
      - /root/.m2
      - .:/maven
      command: mvn -Dbakery.server.port=8080 -Dreport.server.port=8080 clean verify
