apiVersion: v1
kind: Template
labels:
  template: wait-run-pod
metadata:
  annotations:
    description: wait server template (run as pod)
    iconClass: icon-beaker
    tags: consol, wait-for-it
    version: 1.1.0
  creationTimestamp: null
  name: wait-run-pod
### template parameter defined via `oc process -f this.yaml -p PARAMETER=value`
parameters:
## REQUIRED
- name: APP_NAME
  required: true
  value: wait-server
- name: BAKERY_BAKERY_URL
  required: true
- name: BAKERY_REPORT_URL
  required: true
### Configuration of OpenShift objects
objects:
### POD config (run one time)
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      application: ${APP_NAME}
      housekeeping: delete
    name: ${APP_NAME}
  spec:
    ### ensure that the pod won't start again
    restartPolicy: Never
    dnsPolicy: ClusterFirst
    terminationGracePeriodSeconds: 5
    containers:
    - name: ${APP_NAME}-bakery
      image: toschneck/wait-for-it:latest
      imagePullPolicy: Always
      args:
        - "${BAKERY_BAKERY_URL}"
        - "-p"
        - "80"
        - "-t"
        - "300"
    - name: ${APP_NAME}-report
      image: toschneck/wait-for-it:latest
      imagePullPolicy: Always
      args:
        - "${BAKERY_REPORT_URL}"
        - "-p"
        - "80"
        - "-t"
        - "300"


      